# Form implementation generated from reading ui file 'frontend/ui/students_ui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(859, 582)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 771, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_lbl = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.name_lbl.setFont(font)
        self.name_lbl.setObjectName("name_lbl")
        self.verticalLayout.addWidget(self.name_lbl)
        self.table = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.student_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.student_btn.setFont(font)
        self.student_btn.setObjectName("student_btn")
        self.horizontalLayout_2.addWidget(self.student_btn)
        self.jury_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.jury_btn.setFont(font)
        self.jury_btn.setObjectName("jury_btn")
        self.horizontalLayout_2.addWidget(self.jury_btn)
        self.sec_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.sec_btn.setFont(font)
        self.sec_btn.setObjectName("sec_btn")
        self.horizontalLayout_2.addWidget(self.sec_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.res_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.res_btn.setFont(font)
        self.res_btn.setObjectName("res_btn")
        self.verticalLayout.addWidget(self.res_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Студенты"))
        self.name_lbl.setText(_translate("Form", "TextLabel"))
        self.student_btn.setText(_translate("Form", "Студенты"))
        self.jury_btn.setText(_translate("Form", "Жюри"))
        self.sec_btn.setText(_translate("Form", "Секции"))
        self.res_btn.setText(_translate("Form", "Отчёт"))
